### ISSUE TITLE
How to build on VS 2022 (Version 17.8.3) with target Windows Machine

### ISSUE THREAD

**Issue by mikan66** [FmgLib/FmgLib.MauiMarkup#34]
I am curious about your project and I tried to build Master and also 8.0.7 tag.  Both give similar errors to 8.0.7:

![image](https://github.com/FmgLib/FmgLib.MauiMarkup/assets/4913543/767d096a-c673-464d-969b-abed2f1531b0)

**Comment by gonultasmf** [comment]
Did you pull an existing project? Or did you use the FmgLib.MauiMarkup library in a scratch project? If you can elaborate a little more, I will help you immediately.

**Comment by mikan66** [comment]
Since this question, I have abandoned all MauiMarkup use due to poor documentation and examples across the community, (not in regard to this project).  I'm going back to XAML.  Regarding this question, I had tried to pull this repo and build it directly on the given date.

**Comment by gonultasmf** [comment]
I will work on documentation in line with your comments. I'm sorry I couldn't get back on time.
