### ISSUE TITLE
Add Compiled bindings

### ISSUE THREAD

**Issue by taublast** [FmgLib/FmgLib.MauiMarkup#68]
As title, we have compiled bindings support in xaml and in some alternative libs like community toolkit markup, if it was here would be a killer.

**Comment by gonultasmf** [comment]
Sounds very good.  Could you elaborate a little more?  Let's start right away.

**Comment by taublast** [comment]
For example, when using FmgLib.MauiMarkup and community toolkit markup a simple binding would be:

`.Bind(VisualElement.BackgroundColorProperty, nameof(vm.TestColor))`

In community toolkit can also use a "compiled" binding (how they call them for xaml), of "typed binding" by specifying a direct getter from a known type for faster binding:

`.Bind(VisualElement.BackgroundColorProperty, static (TestViewModel vm) => vm.TestColor)`

I didn't find a similar way in FmgLib.MauiMarkup, please correct me if I misslooked. I have found only https://github.com/FmgLib/FmgLib.MauiMarkup/blob/3df9e92e6be8acd3c3efecc84b9af5ffbdec52dd/libs/FmgLib.MauiMarkup/Extensions/BindableObjectExtension.cs#L7

The community toolkit related source: 
https://github.com/CommunityToolkit/Maui.Markup/blob/481f3e4da53095bda20c9701acf8917237f29c89/src/CommunityToolkit.Maui.Markup/TypedBindingExtensions.cs#L10

**Comment by gonultasmf** [comment]
Actually, this feature is also available in the FmgLib.Markup library. And the place you found is correct. The issue arose just because you couldn't figure out how to use it :(

The usage is actually easier than the CommunityToolkit markup. You can use it in two ways.
The first way is very similar to CommunityToolkit markup like this:
```csharp
new CollectionView()
    .SelectionMode(SelectionMode.None)
    .Bind(CollectionView.ItemsSourceProperty, "Products");

```

The second way is nicer and has a structure very close to XAML syntax:
```csharp
new ImageButton()
    .Source("filter.png")
    .SizeRequest(40, 40)
    .Command(e => e.Path("ShowFilterPopupCommand"))
    .Column(1)
    .AlignEnd();

```
or
```csharp
new CartesianChart()
    .Row(2)
    .Series(e => e.Path("Series"))
    .XAxes(e => e.Path("XAxes"))
    .ZoomMode(ZoomX);

```
or
```csharp
new DXCollectionView()
    .ItemsSource(e => e.Path("Items"))
    .IsRefreshing(e => e.Path("IsRefreshing").BindingMode(BindingMode.TwoWay))
    .IsLoadMoreEnabled(e => e.Path("IsLoadMoreEnabled"))
    .LoadMoreCommand(e => e.Path("LoadMoreCommand"))
    .IndicatorColor(DeepSkyBlue);

```
or
```csharp
new VerticalStackLayout()
.Spacing(15)
.Row(1)
.Children( 
    new TextEdit()
    .LabelText("Email")
    .Text(e => e.Path("Login.Username")),

    new PasswordEdit()
    .LabelText("Password")
    .Text(e => e.Path("Login.Password")),

    new Grid()
    .ColumnDefinitions(e => e.Star().Star())
    .FillHorizontal()
    .Children(
        new CheckEdit()
        .Label("Remember for 30 days")
        .AlignStart()
        .IsChecked(e => e.Path("Login.IsRememberMe")),

         new Label()
         .Text("Forget password")
         .TextColor(DeepSkyBlue)
         .TextDecorations(Underline)
         .TextCenterVertical()
         .Column(1)
         .AlignEnd()
    )
),
```

I will add a detailed section about this to the documentation site https://fmgyazilim.com/en/fmglibmauimarkup.

**Comment by gonultasmf** [comment]
If you don't have any other questions on the subject, I will close the issue :)

**Comment by taublast** [comment]
From what I see in the example above we are still using a named binding that will use reflection at runtime to find a property by name in the binding context object, whatever the type, which is relatively slow. While typed binding uses a faster way to set it as the binding context type is already assigned at compile time.

**Comment by gonultasmf** [comment]
Would it be sufficient for you if I provide the Bind extension methods offered by the community toolkit markup library?

**Comment by taublast** [comment]
Here is the reasoning behind using compiled/typed bindings:
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-8.0
Unfortunately MSFT did not seem to provide a simple way to do the same in code-behind, only in xaml.
Some fluent syntax libraries like 
* https://github.com/VincentH-Net/CSharpForMarkup
* https://github.com/CommunityToolkit/Maui.Markup
worked around it, so I just thought your awesome library could implement this feature too, not really my call to make. :)

**Comment by gonultasmf** [comment]
Actually, CommunityToolkit.Maui.Markup essentially uses the Bind method that is included in my library. Nevertheless, I will base it on the CommunityToolkit.Maui.Markup library to provide the same variety of Bind methods in my library as well. I will be releasing this soon as a prerelease version.
thanks :)

**Comment by gonultasmf** [comment]
The relevant commit has been made and published(8.3.1-prev1.0.2). 555d65136e27751d472df9a03ac8e912d250563a

**Comment by powerdude** [comment]
hi @gonultasmf , sorry to comment on a closed thread, but has this feature been added.  I looked at the commit referenced above and that doesn't seem to do what's asked.  I also looked at this commit https://github.com/FmgLib/FmgLib.MauiMarkup/commit/806f258e12354647ba569785cbff7e354f18bd0e and that didn't seem to have code to allow someone to use `Bind(BackGroundColorProper, static (TestViewModel vm) => vm.TestColor`).  It would be a great addition to not have to use magic strings or `nameof(TestViewModel.TestColor)`, especially since the the latter doesn't work if there's a chain of properties.

**Comment by gonultasmf** [comment]
The recommended usage for FmgLib.MauiMarkup is as follows for your request:
```csharp
new Button().BackgroundColor(e => e.Path("TestColor"))
```
This usage also works just like Bind.

**Comment by powerdude** [comment]
Thanks for the reply.  No chance in adding support to use expressions as this seems less than ideal relying on strings in this way?  It is why other libraries have it.  Particularly, doing something like this is less ergonomic:

```csharp
new Button().BackgroundColor(e => e.Path($"{nameof(SomeChildOfVM)}.{nameof(SomeChildOfVM.TestColor)}"))
```

versus
```csharp
new Button().BackgroundColor( e=> e.Path( static (ParentVm vm) => vm.SomeChildOfVM.TestColor));
```

**Comment by powerdude** [comment]
This is the [class ](https://github.com/CommunityToolkit/Maui.Markup/blob/main/src/CommunityToolkit.Maui.Markup/TypedBindingExtensions.cs)I'm referring to in the Maui toolkit.

**Comment by gonultasmf** [comment]
Adding the system in the Maui toolkit will do the trick at this point.

Can you open a new issue for this?

**Comment by powerdude** [comment]
I've been thinking about this some more and if you do this, here's one way it can look for an API that could be easy for a user:

```csharp
new Button().With<ParentVm>().BackgroundColor(e=>e.Path(x=>x.SomeChildOfVM.TestColor));
```
or
```csharp
new Button().BackgroundColor<ParentVm>(e=>e.Path(x=>x.SomeChildOfVM.TestColor));
```

**Comment by gonultasmf** [comment]
@powerdude @taublast  With new version 9.0.2, there is now a usage like this:

```csharp
new Label().Text(e => e.Getter(static (MyViewModel model) => model.Username));
```
